name: Build Anime APK

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. جلب الكود من المستودع
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. إعداد بايثون وتثبيت المكتبات المساعدة للأنمي
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. تثبيت مفسر الطلبات والمكتبات الأساسية
      - name: Install Dependencies
        run: |
          pip install requests

      # 4. استخدام أداة البناء الرسمية والذكية لـ Flet (تتخطى مشاكل الأسئلة والـ Flutter تلقائياً)
      - name: Build Flet APK using Official Action
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk

      # 5. رفع ملف الـ APK لتنزيله على هاتفك مباشرة
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: anime-Palestine-App
          path: build/outputs/apk/debug/*.apk
